In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
arr = np.array(mylist)

In [8]:
arr

array([1, 2, 3])

In [9]:
type(arr)

numpy.ndarray

In [15]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
arr1 = np.array(mylist)

In [18]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr1[0]

array([1, 2, 3])

In [21]:
arr1[0][1]

2

In [22]:
np.array(arr1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
mymatrix = np.array(arr1)

In [24]:
mymatrix.shape

(3, 3)

In [28]:
mymatrix.T          # .T is transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
list1 = [1,2,3,4,5,6,7]

In [32]:
list1[0:5:2]

[1, 3, 5]

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [40]:
np.arange(0,11,2)        # it gives integer output

array([ 0,  2,  4,  6,  8, 10])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros(5)        # it gives float output

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
arr2 = np.ones((5,10))     

In [47]:
np.array(arr2)      # it gives float output

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### NUMPY BORADCASTING WITH + AND *

In [49]:
np.ones((5,10))+8

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
mymatrix + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [54]:
[1,1,1]+1

TypeError: can only concatenate list (not "int") to list

In [55]:
[1,1,1]+[1,1,1]

[1, 1, 1, 1, 1, 1]

In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [57]:
np.ones(4)*2

array([2., 2., 2., 2.])

In [58]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [59]:
np.ones((1,4))*2

array([[2., 2., 2., 2.]])

In [61]:
np.ones(20) * 121

array([121., 121., 121., 121., 121., 121., 121., 121., 121., 121., 121.,
       121., 121., 121., 121., 121., 121., 121., 121., 121.])

In [62]:
# but in python list

In [64]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [65]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### NOTE:  In list the meaning of '*' and '+' is concatenation but in numpy it is addition and multiplication

### Linearly Spaced Elements in an array

In [71]:
np.linspace(0,10,2)

array([ 0., 10.])

In [72]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [73]:
np.linspace(0,10,3, endpoint = False)

array([0.        , 3.33333333, 6.66666667])

In [74]:
np.linspace(0,120,28, endpoint = False)

array([  0.        ,   4.28571429,   8.57142857,  12.85714286,
        17.14285714,  21.42857143,  25.71428571,  30.        ,
        34.28571429,  38.57142857,  42.85714286,  47.14285714,
        51.42857143,  55.71428571,  60.        ,  64.28571429,
        68.57142857,  72.85714286,  77.14285714,  81.42857143,
        85.71428571,  90.        ,  94.28571429,  98.57142857,
       102.85714286, 107.14285714, 111.42857143, 115.71428571])

In [77]:
np.linspace(0,120,28, endpoint = True)

array([  0.        ,   4.44444444,   8.88888889,  13.33333333,
        17.77777778,  22.22222222,  26.66666667,  31.11111111,
        35.55555556,  40.        ,  44.44444444,  48.88888889,
        53.33333333,  57.77777778,  62.22222222,  66.66666667,
        71.11111111,  75.55555556,  80.        ,  84.44444444,
        88.88888889,  93.33333333,  97.77777778, 102.22222222,
       106.66666667, 111.11111111, 115.55555556, 120.        ])

In [75]:
len(np.linspace(0,120,28, endpoint = False))

28

In [76]:
len(np.linspace(0,120,28, endpoint = True))

28

In [79]:
np.linspace(0,10,3, endpoint = False)

array([0.        , 3.33333333, 6.66666667])

### Identity matrix

In [80]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [82]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [85]:
np.eye(3,3,1)      # +1 upper triangular matrix

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [87]:
np.eye(3,3,-1)      # -1 lower triangular matrix

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [89]:
np.eye(5,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [90]:
np.eye(5,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [92]:
np.eye(5,5,3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
np.eye(5,5,4)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])