In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0: : ]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
new_arr = arr/2

In [14]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## NOTE: slice of an array, it points to the original array

In [20]:
slice_of_arr = arr[:5]

In [21]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [22]:
slice_of_arr[:]

array([0, 1, 2, 3, 4])

In [23]:
slice_of_arr[:] = 99

In [24]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [25]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## Explicitly making a copy of the numpy array

In [28]:
arr = np.arange(0,11)

In [29]:
arr_copy = arr.copy()

In [30]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr_copy[:] = 101

In [32]:
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing on 2D array

In [34]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d.shape

(3, 3)

In [41]:
arr_2d[0]   # 1st row

array([ 5, 10, 15])

In [39]:
arr_2d[1]

array([20, 25, 30])

In [47]:
arr_2d[:,0]  # 1st column

array([ 5, 20, 35])

In [50]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [51]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [52]:
arr_2d[:2,:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [53]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])