In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [7]:
1/arr

/var/folders/7h/25w2ffw11bq8pwdqy80tr7v40000gn/T/ipykernel_1710/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
a = 1/arr

/var/folders/7h/25w2ffw11bq8pwdqy80tr7v40000gn/T/ipykernel_1710/2740109360.py:1: RuntimeWarning: divide by zero encountered in divide
  a = 1/arr


In [12]:
a.dtype

dtype('float64')

In [13]:
type(a)

numpy.ndarray

In [14]:
arr/arr

/var/folders/7h/25w2ffw11bq8pwdqy80tr7v40000gn/T/ipykernel_1710/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
np.log(arr)

/var/folders/7h/25w2ffw11bq8pwdqy80tr7v40000gn/T/ipykernel_1710/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
arr.sum()

45

In [20]:
arr.mean()

4.5

In [21]:
arr.max()

9

In [22]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [23]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr_2d.sum()

78

In [25]:
arr_2d.shape

(3, 4)

In [26]:
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])

In [27]:
arr_2d.sum(axis = 1)

array([10, 26, 42])

## PANDA SERIES

In [28]:
import numpy as np
import pandas as pd

In [49]:
labels = ['a','b','c']

In [30]:
mylist = [10,20,30]

In [33]:
arr = np.array(mylist)      # index a,b,c,d and values are 10,20,30

In [34]:
arr

array([10, 20, 30])

In [35]:
d = {'a':10,'b':20,'c':30}

In [36]:
d

{'a': 10, 'b': 20, 'c': 30}

In [39]:
pd.Series()

Series([], dtype: object)

In [40]:
pd.Series(data = mylist)

0    10
1    20
2    30
dtype: int64

In [41]:
pd.Series(data = arr)

0    10
1    20
2    30
dtype: int64

In [42]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [46]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [50]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int64

In [53]:
pd.Series(data=arr, index=[1,1,2])

1    10
1    20
2    30
dtype: int64

In [54]:
ser1 = pd.Series(data=[1,2,3,4], index = ["USA","Germany","USSR","Japan"])

In [55]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [56]:
ser1['USA']

1

In [57]:
ser2 = pd.Series(data=[1,4,5,6], index = ["USA","Germany","Italy","Japan"])

In [58]:
ser2

USA        1
Germany    4
Italy      5
Japan      6
dtype: int64

In [59]:
ser1 + ser2

Germany     6.0
Italy       NaN
Japan      10.0
USA         2.0
USSR        NaN
dtype: float64